project:
  type: website
  output-dir: docs

website:
  title: "reports"
  navbar:
    left:
      - href: work/computeTEW.Rmd
        text: "Topographic Exposure to Wind"
      
      - text: "Extract Data"
        menu: 
          - href: work/getDTM.Rmd
            text: "Digital Terrain Model"
          - href: work/getSentinel.Rmd
            text: "Vegetation Data"
            
      - text: "Extended work"
        menu: 
          - href: work/melissa.Rmd
            text: "Melissa"
          - href: work/reunion.Rmd
            text: "Réunion"
      
      
      - text: "Weekly reports"
        menu:

          # --- JANVIER ---
          - href: hebdos/january.Rmd
            text: "Janvier"
          
          # --- FÉVRIER ---
          - href: hebdos/february.Rmd
            text: "Février"
          - href: work/summary1902.Rmd
            text: "Réunion 19/02"
          
          # --- MARS ---
          - href: hebdos/march.Rmd
            text: "Mars"
          - href: work/brutimages.Rmd
            text: "Images brutes Mayotte"
          - href: work/mbouzi.Rmd
            text: "Mbouzi"

          
          # --- AVRIL ---
          - href: hebdos/april.Rmd
            text: "Avril"
            text: "Tests modèles"
          
          # --- MAI ---
          - href: hebdos/may.Rmd
            text: "Mai"
      
      - href: about.qmd
        text: "A propos"

      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

